
package snippets.jee.ws.soap.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CourseManagementService", targetNamespace = "http://soap.ws.jee.snippets/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CourseManagementService {


    /**
     * 
     * @param arg0
     * @return
     *     returns snippets.jee.ws.soap.client.Course
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCourse", targetNamespace = "http://soap.ws.jee.snippets/", className = "snippets.jee.ws.soap.client.GetCourse")
    @ResponseWrapper(localName = "getCourseResponse", targetNamespace = "http://soap.ws.jee.snippets/", className = "snippets.jee.ws.soap.client.GetCourseResponse")
    @Action(input = "http://soap.ws.jee.snippets/CourseManagementService/getCourseRequest", output = "http://soap.ws.jee.snippets/CourseManagementService/getCourseResponse")
    public Course getCourse(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<snippets.jee.ws.soap.client.Course>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCourses", targetNamespace = "http://soap.ws.jee.snippets/", className = "snippets.jee.ws.soap.client.GetCourses")
    @ResponseWrapper(localName = "getCoursesResponse", targetNamespace = "http://soap.ws.jee.snippets/", className = "snippets.jee.ws.soap.client.GetCoursesResponse")
    @Action(input = "http://soap.ws.jee.snippets/CourseManagementService/getCoursesRequest", output = "http://soap.ws.jee.snippets/CourseManagementService/getCoursesResponse")
    public List<Course> getCourses();

}
