
package snippets.jee.ws.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CourseManagementService", targetNamespace = "http://soap.ws.jee.snippets/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
    @XmlSeeAlso({
    ObjectFactory.class
    })
public interface CourseManagementService {


    /**
     * 
     * @return
     *     returns snippets.jee.ws.soap.client.Courses
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.ws.jee.snippets/CourseManagementService/getCoursesRequest", output = "http://soap.ws.jee.snippets/CourseManagementService/getCoursesResponse")
    public Courses getCourses();

    /**
     * 
     * @param courseId
     * @return
     *     returns snippets.jee.ws.soap.client.Course
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap.ws.jee.snippets/CourseManagementService/getCourseRequest", output = "http://soap.ws.jee.snippets/CourseManagementService/getCourseResponse")
    public Course getCourse(
            @WebParam(name = "courseId", partName = "courseId")
            int courseId);

}
